### ISSUE TITLE
Access violation in poodinis.container.getExistingRegistration

### ISSUE THREAD

**Issue by Heromyth** [mbierlee/poodinis#16]
This happens in release mode.

Compiler: DMD32 D Compiler v2.072.2
OS: Win10 x64
Test: example\quickstart\app.d

**Comment by mbierlee** [comment]
Thank you for reporting this issue! After some investigation this seems to be caused by a bug in the DRuntime. I've filed it under https://issues.dlang.org/show_bug.cgi?id=17088

Unfortunately I couldn't find an easy workaround at this time. If the dlang issue is not solved within a considerable amount of time I will see if I can re-architect some things to fix it.

**Comment by mbierlee** [comment]
In DMD 2.075.0 this issue, at least for Poodinis, seems to be fixed
