### ISSUE TITLE
inject properties with @Value

### ISSUE THREAD

**Issue by SingingBush** [mbierlee/poodinis#4]
hello again. Do you have any plans to introduce Springs `@Value` annotation? I'm currently using [properd](https://github.com/mbierlee/properd) to handle my database properties before registering all my dependencies to the DependencyContainer.

It would be a little nicer though if poodinis could do the following:

```
@Value("db.domain:localhost") // find a property named db.domain or default to localhost
string dbHost;

@Value("db.port") // find a property named db.port or null
int dbPort;
```

**Comment by mbierlee** [comment]
This would be nice indeed but I think it would be outside of the scope of Poodinis at this moment. Poodinis is meant to be purely DI. Already it is becoming more and more like the core Spring framework. I will see if I can make context registration extendable so that another library could be made do this instead.

**Comment by mbierlee** [comment]
Will be delivered in the next version of Poodinis. A value injector using proper-d will be released in another project.
